/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createUpdatedProviderListing = /* GraphQL */ `
  mutation CreateUpdatedProviderListing(
    $input: CreateUpdatedProviderListingInput!
    $condition: ModelUpdatedProviderListingConditionInput
  ) {
    createUpdatedProviderListing(input: $input, condition: $condition) {
      premiumAccreditations {
        name
        image
        year
      }
      premiumServices {
        title
        content
      }
      premiumOverview
      premiumPeople {
        name
        title
        image
        location
        spiel
        specialty
        languages
      }
      premiumFees {
        title
        price
      }
      premiumFaqs {
        question
        answer
      }
      features
      jurisdiction
      languages
      editors
      query
      name
      site
      type
      subtypes
      category
      phone
      full_address
      borough
      street
      city
      city_key
      url_key
      postal_code
      state
      us_state
      country
      country_code
      latitude
      longitude
      time_zone
      plus_code
      rating
      reviews
      reviews_link
      reviews_tags
      reviews_per_score
      photos_count
      photo
      street_view
      located_in
      working_hours {
        Monday
        Tuesday
        Wednesday
        Thursday
        Friday
        Saturday
        Sunday
      }
      popular_times
      business_status
      about
      range
      posts
      logo
      description
      verified
      owner_id
      owner_title
      owner_link
      reservation_links
      booking_appointment_link
      menu_link
      order_links
      location_link
      place_id
      google_id
      cid
      reviews_id
      located_google_id
      email_1
      email_1_full_name
      email_1_title
      email_2
      email_2_full_name
      email_2_title
      email_3
      email_3_full_name
      email_3_title
      phone_1
      phone_2
      phone_3
      facebook
      instagram
      linkedin
      medium
      reddit
      skype
      snapchat
      telegram
      whatsapp
      twitter
      vimeo
      youtube
      github
      crunchbase
      title
      generator
      keywords
      deleted
      pending
      email
      membership
      createdAt
      updatedAt
      owner
    }
  }
`;
export const updateUpdatedProviderListing = /* GraphQL */ `
  mutation UpdateUpdatedProviderListing(
    $input: UpdateUpdatedProviderListingInput!
    $condition: ModelUpdatedProviderListingConditionInput
  ) {
    updateUpdatedProviderListing(input: $input, condition: $condition) {
      premiumAccreditations {
        name
        image
        year
      }
      premiumServices {
        title
        content
      }
      premiumOverview
      premiumPeople {
        name
        title
        image
        location
        spiel
        specialty
        languages
      }
      premiumFees {
        title
        price
      }
      premiumFaqs {
        question
        answer
      }
      features
      jurisdiction
      languages
      editors
      query
      name
      site
      type
      subtypes
      category
      phone
      full_address
      borough
      street
      city
      city_key
      url_key
      postal_code
      state
      us_state
      country
      country_code
      latitude
      longitude
      time_zone
      plus_code
      rating
      reviews
      reviews_link
      reviews_tags
      reviews_per_score
      photos_count
      photo
      street_view
      located_in
      working_hours {
        Monday
        Tuesday
        Wednesday
        Thursday
        Friday
        Saturday
        Sunday
      }
      popular_times
      business_status
      about
      range
      posts
      logo
      description
      verified
      owner_id
      owner_title
      owner_link
      reservation_links
      booking_appointment_link
      menu_link
      order_links
      location_link
      place_id
      google_id
      cid
      reviews_id
      located_google_id
      email_1
      email_1_full_name
      email_1_title
      email_2
      email_2_full_name
      email_2_title
      email_3
      email_3_full_name
      email_3_title
      phone_1
      phone_2
      phone_3
      facebook
      instagram
      linkedin
      medium
      reddit
      skype
      snapchat
      telegram
      whatsapp
      twitter
      vimeo
      youtube
      github
      crunchbase
      title
      generator
      keywords
      deleted
      pending
      email
      membership
      createdAt
      updatedAt
      owner
    }
  }
`;
export const deleteUpdatedProviderListing = /* GraphQL */ `
  mutation DeleteUpdatedProviderListing(
    $input: DeleteUpdatedProviderListingInput!
    $condition: ModelUpdatedProviderListingConditionInput
  ) {
    deleteUpdatedProviderListing(input: $input, condition: $condition) {
      premiumAccreditations {
        name
        image
        year
      }
      premiumServices {
        title
        content
      }
      premiumOverview
      premiumPeople {
        name
        title
        image
        location
        spiel
        specialty
        languages
      }
      premiumFees {
        title
        price
      }
      premiumFaqs {
        question
        answer
      }
      features
      jurisdiction
      languages
      editors
      query
      name
      site
      type
      subtypes
      category
      phone
      full_address
      borough
      street
      city
      city_key
      url_key
      postal_code
      state
      us_state
      country
      country_code
      latitude
      longitude
      time_zone
      plus_code
      rating
      reviews
      reviews_link
      reviews_tags
      reviews_per_score
      photos_count
      photo
      street_view
      located_in
      working_hours {
        Monday
        Tuesday
        Wednesday
        Thursday
        Friday
        Saturday
        Sunday
      }
      popular_times
      business_status
      about
      range
      posts
      logo
      description
      verified
      owner_id
      owner_title
      owner_link
      reservation_links
      booking_appointment_link
      menu_link
      order_links
      location_link
      place_id
      google_id
      cid
      reviews_id
      located_google_id
      email_1
      email_1_full_name
      email_1_title
      email_2
      email_2_full_name
      email_2_title
      email_3
      email_3_full_name
      email_3_title
      phone_1
      phone_2
      phone_3
      facebook
      instagram
      linkedin
      medium
      reddit
      skype
      snapchat
      telegram
      whatsapp
      twitter
      vimeo
      youtube
      github
      crunchbase
      title
      generator
      keywords
      deleted
      pending
      email
      membership
      createdAt
      updatedAt
      owner
    }
  }
`;
